from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(r"F:/学校/病虫害识别/ai_model_training")
REPORTS = ROOT / "reports"


def main() -> None:
    planning = {
        "round": "Phone-35C",
        "mode": "planning_only",
        "baseline": {
            "phone_35a_map50": 0.0978907154772983,
            "phone_35a_no_detection_ratio": 1.0,
            "phone_35b_map50": 0.3872184938941021,
            "phone_35b_conf025_no_detection_ratio": 0.15,
            "phone_35b_conf010_avg_boxes_per_image": 8.0,
        },
        "dataset_audit": {
            "dataset_yaml_exists": True,
            "train_val_test_paths_exist": True,
            "split_counts": {
                "train": {"images": 348, "labels": 348},
                "val": {"images": 100, "labels": 100},
                "test": {"images": 52, "labels": 52},
            },
            "names": [
                "bacterial_blight",
                "blast",
                "brown_spot",
                "tungro",
            ],
            "empty_label_files": 0,
            "bad_label_lines": 0,
            "unmatched_images": 0,
            "unmatched_labels": 0,
            "path_drift_detected": False,
            "data_source_switch_risk": "LOW; 35A and 35B both point to rice_phone_rgb_riceseg_preview_500_revised_v0_1",
        },
        "controlled_35d_config": {
            "model": "yolov8n.pt",
            "pretrained": True,
            "resume": False,
            "data_yaml": "F:/学校/病虫害识别/ai_model_training/datasets/rice_phone_rgb_riceseg_preview_500_revised_v0_1/data.yaml",
            "dataset_root": "F:/学校/病虫害识别/ai_model_training/datasets/rice_phone_rgb_riceseg_preview_500_revised_v0_1",
            "epochs": 10,
            "imgsz": 640,
            "batch": 8,
            "device": "0",
            "workers": 0,
            "seed": 2026,
            "patience": 20,
            "cache": False,
            "optimizer": "auto",
            "lr0": 0.003,
            "project": "F:/学校/病虫害识别/ai_model_training/experiments/phone_rgb_yolo/runs",
            "name": "controlled_exp_phone_riceseg_preview500_revised_v0_1_10epoch",
            "output_naming_rule": "new run name only; must not overwrite 35A sanity or 35B short experimental",
            "comparison_policy": "keep dataset/imgsz/model family fixed; change only epochs from 5 to 10",
        },
        "next_round_commands": {
            "project_script": "C:/Users/13010/anaconda3/envs/torchgpu/python.exe scripts/train_yolo.py --config configs/phone_riceseg_preview500_revised_readiness.yaml --epochs 10 --imgsz 640 --batch 8 --device 0 --name controlled_exp_phone_riceseg_preview500_revised_v0_1_10epoch --execute",
            "yolo_cli_equivalent": "yolo detect train model=yolov8n.pt data=F:/学校/病虫害识别/ai_model_training/datasets/rice_phone_rgb_riceseg_preview_500_revised_v0_1/data.yaml epochs=10 imgsz=640 batch=8 device=0 workers=0 seed=2026 project=F:/学校/病虫害识别/ai_model_training/experiments/phone_rgb_yolo/runs name=phone_riceseg_35d_10epoch_controlled",
        },
        "risk_assessment": {
            "execute_35d_is_worth_it": True,
            "overfit_risk": "MODERATE; 35B improved strongly on 5 epochs, so 10 epochs is justified, but dataset scale is still only 500 images and needs controlled evaluation.",
            "false_positive_risk": "MODERATE_TO_HIGH at low confidence; conf=0.10 avg_boxes_per_image=8.0 already indicates noisy behavior.",
            "conf_sweep_should_wait_until_35e": True,
            "why_not_30_epoch_now": "10 epoch is the right controlled next step because 35B already improved sharply and the current unknown is stability, not raw training duration ceiling.",
            "human_review_should_wait_until_35f": True,
            "notes": [
                "35D should test learning continuation under fixed variables.",
                "35E should own validate/infer/conf-sweep evidence.",
                "35F should own visual judgment of predicted boxes, not 35C.",
            ],
        },
        "gate": {
            "phone_riceseg_35c_controlled_planning_gate": "PASS",
            "next_allowed_stage": "Phone-35D_10epoch_controlled_training",
            "training_executed_this_round": "NO",
            "backend_modified_this_round": "NO",
            "env_modified_this_round": "NO",
            "labels_modified_this_round": "NO",
            "weights_overwritten_this_round": "NO",
        },
    }

    md_lines = [
        "# Phone RiceSeg 35C 10epoch Controlled Planning Report",
        "",
        "## Round Scope",
        "",
        "- mode: `planning_only`",
        "- training executed this round: `NO`",
        "- backend modified this round: `NO`",
        "- env modified this round: `NO`",
        "- labels modified this round: `NO`",
        "- weights overwritten this round: `NO`",
        "",
        "## Locked Baseline",
        "",
        "- `35A mAP50 = 0.0978907154772983`",
        "- `35A no_detection_ratio = 1.0`",
        "- `35B mAP50 = 0.3872184938941021`",
        "- `35B conf=0.25 no_detection_ratio = 0.15`",
        "- `35B conf=0.10 avg_boxes_per_image = 8.0`",
        "",
        "## Dataset Read-Only Audit",
        "",
        "- dataset yaml exists: `YES`",
        "- train/val/test paths exist: `YES`",
        "- train images/labels: `348 / 348`",
        "- val images/labels: `100 / 100`",
        "- test images/labels: `52 / 52`",
        "- class names: `bacterial_blight / blast / brown_spot / tungro`",
        "- empty label files: `0`",
        "- bad label lines: `0`",
        "- unmatched images: `0`",
        "- unmatched labels: `0`",
        "- obvious path drift: `NO`",
        "- data source switch risk versus 35A/35B: `LOW`",
        "",
        "## 35D Controlled Training Plan",
        "",
        "- model: `yolov8n.pt`",
        "- pretrained: `true`",
        "- resume: `false`",
        "- data_yaml: `F:/学校/病虫害识别/ai_model_training/datasets/rice_phone_rgb_riceseg_preview_500_revised_v0_1/data.yaml`",
        "- epochs: `10`",
        "- imgsz: `640`",
        "- batch: `8`",
        "- device: `0`",
        "- workers: `0`",
        "- seed: `2026`",
        "- patience: `20`",
        "- cache: `false`",
        "- project: `F:/学校/病虫害识别/ai_model_training/experiments/phone_rgb_yolo/runs`",
        "- run_name: `controlled_exp_phone_riceseg_preview500_revised_v0_1_10epoch`",
        "- output policy: `must not overwrite 35A / 35B runs`",
        "",
        "## 35D Suggested Commands",
        "",
        "```bash",
        planning["next_round_commands"]["project_script"],
        "```",
        "",
        "```bash",
        planning["next_round_commands"]["yolo_cli_equivalent"],
        "```",
        "",
        "## Risk Judgment",
        "",
        "- 35D worth executing: `YES`",
        "- overfit risk: `MODERATE`",
        "- false-positive / noisy-box risk at low conf: `MODERATE_TO_HIGH`",
        "- conf sweep should stay in 35E: `YES`",
        "- do 10 epoch before 30 epoch: `YES`",
        "- human review should stay in 35F: `YES`",
        "",
        "## Gate",
        "",
        "- phone_riceseg_35c_controlled_planning_gate: `PASS`",
        "- next_allowed_stage: `Phone-35D_10epoch_controlled_training`",
        "- training_executed_this_round: `NO`",
        "- backend_modified_this_round: `NO`",
        "- env_modified_this_round: `NO`",
        "- labels_modified_this_round: `NO`",
        "- weights_overwritten_this_round: `NO`",
    ]

    prompt_lines = [
        "# Phone-35D: 10 epoch controlled experimental training",
        "",
        "Current project directory:",
        "`F:/学校/病虫害识别/ai_model_training`",
        "",
        "## Hard Boundaries",
        "",
        "- Execute exactly `10 epoch` only.",
        "- Do not run `20 / 30 epoch`.",
        "- Do not resume from the 5 epoch weight.",
        "- Do not modify raw dataset files, labels, backend, or real `.env`.",
        "- Do not overwrite 35A or 35B runs.",
        "- Do not write any result as formal model performance.",
        "",
        "## Locked Baseline",
        "",
        "- `35A mAP50 = 0.0978907154772983`",
        "- `35A no_detection_ratio = 1.0`",
        "- `35B mAP50 = 0.3872184938941021`",
        "- `35B conf=0.25 no_detection_ratio = 0.15`",
        "- `35B conf=0.10 avg_boxes_per_image = 8.0`",
        "",
        "## Preconditions",
        "",
        "- dataset: `datasets/rice_phone_rgb_riceseg_preview_500_revised_v0_1`",
        "- machine_check: `PASS`",
        "- manual_gate: `PASS`",
        "- environment: `torchgpu READY_GPU`",
        "- 35C planning gate: `PASS`",
        "",
        "## Execute This Training Command",
        "",
        "```bash",
        planning["next_round_commands"]["project_script"],
        "```",
        "",
        "## Required Artifact Checks",
        "",
        "- `weights/best.pt`",
        "- `weights/last.pt`",
        "- `results.csv`",
        "- `args.yaml`",
        "- actual epoch count must be `10`",
        "- no `NaN`",
        "- no class-id error",
        "- no label out-of-range error",
        "",
        "## Required Outputs",
        "",
        "- `reports/phone_riceseg_10epoch_train_stdout.log`",
        "- `reports/phone_riceseg_10epoch_train_stderr.log`",
        "- `reports/phone_riceseg_10epoch_artifact_check.json`",
        "- `reports/phone_riceseg_10epoch_artifact_check.md`",
        "- `reports/thirty_fifth_round_d_phone_riceseg_10epoch_training_report.md`",
        "",
        "## Gate Format",
        "",
        "- `training_complete` only if 10 epoch finishes and artifacts exist",
        "- still `experimental only`",
        "- still `not backend-ready`",
    ]

    (REPORTS / "phone_riceseg_35c_10epoch_controlled_planning_report.json").write_text(
        json.dumps(planning, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (REPORTS / "phone_riceseg_35c_10epoch_controlled_planning_report.md").write_text(
        "\n".join(md_lines) + "\n",
        encoding="utf-8",
    )
    (REPORTS / "phone_riceseg_35d_next_training_prompt.md").write_text(
        "\n".join(prompt_lines) + "\n",
        encoding="utf-8",
    )
    print("OK")


if __name__ == "__main__":
    main()
