ERROR_INVALID_IMAGE = "INVALID_IMAGE"
ERROR_FILE_TOO_LARGE = "FILE_TOO_LARGE"
ERROR_MODEL = "MODEL_ERROR"
ERROR_STORAGE = "STORAGE_ERROR"
ERROR_RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
ERROR_DATABASE = "DATABASE_ERROR"
ERROR_INTERNAL = "INTERNAL_ERROR"
ERROR_TASK_NOT_FOUND = "TASK_NOT_FOUND"
ERROR_ALERT_NOT_FOUND = "ALERT_NOT_FOUND"

SEVERITY_NONE = "\u65e0\u75c5"
SEVERITY_LIGHT = "\u8f7b\u5ea6"
SEVERITY_MEDIUM = "\u4e2d\u5ea6"
SEVERITY_HEAVY = "\u91cd\u5ea6"

RISK_NORMAL = "normal"
RISK_LOW = "low"
RISK_MEDIUM = "medium"
RISK_HIGH = "high"

DEFAULT_REGION_NAME = "\u672a\u6307\u5b9a\u4e61\u9547"
DEFAULT_SOURCE = "manual_upload"

SOURCE_UAV_RGB = "uav_rgb"
SOURCE_UAV_MS = "uav_ms"
SOURCE_UAV_MULTISPECTRAL = "uav_multispectral"
SOURCE_UAV_VIDEO_FRAME = "uav_video_frame"
SOURCE_PHONE_RGB = "phone_rgb"
SOURCE_PHONE_FOLLOWUP = "phone_followup"
SOURCE_MANUAL_UPLOAD = "manual_upload"
SOURCE_UNKNOWN = "unknown"

ALLOWED_SOURCE_TYPES = {
    SOURCE_UAV_RGB,
    SOURCE_UAV_MS,
    SOURCE_UAV_MULTISPECTRAL,
    SOURCE_UAV_VIDEO_FRAME,
    SOURCE_PHONE_RGB,
    SOURCE_PHONE_FOLLOWUP,
    SOURCE_MANUAL_UPLOAD,
    SOURCE_UNKNOWN,
}

TASK_STATUS_PENDING = "pending"
TASK_STATUS_PROCESSING = "processing"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_PARTIAL_FAILED = "partial_failed"
TASK_STATUS_FAILED = "failed"

ALERT_STATUS_ACTIVE = "active"
ALERT_STATUS_MUTED = "muted"
ALERT_STATUS_RESOLVED = "resolved"
